### ISSUE TITLE
Error(s) installing in Wheezy

### ISSUE THREAD

**Issue by JedMeister** [jone/github-watchlist#5]
TBH I haven't done any troubleshooting and I need to go to bed, but I just tried installing as per README instructions and got a dependnacy issue when running `bin/buildout` so thought I'd post it here...

Here's the tail end of the stacktrace (but I can post more if you want - seems to be pretty clear what the issue is)
````
pkg_resources.VersionConflict: (six 1.1.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.4'))
An error occurred when trying to install unittest2 1.0.1. Look above this message for any errors that were output by easy_install.
While:
  Installing test.
  Getting distribution for 'unittest2'.
Error: Couldn't install: unittest2 1.0.1
````
I fixed that with:
````
sudo pip install six --upgrade
````
Install seemed to complete but there were errors such as:
````
Installed /tmp/easy_install-TQu5dX/unittest2-1.0.1/.eggs/linecache2-1.0.0-py2.7.egg
/turnkey/non/github-watchlist/eggs/setuptools-15.2-py2.7.egg/setuptools/dist.py:291: UserWarning: The version specified (<__main__.late_version instance at 0x2b1b680>) is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
````
And
````
Installed /tmp/easy_install-HqH4Nr/linecache2-1.0.0/.eggs/pbr-0.10.8-py2.7.egg
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/linecache2/tests/inspect_fodder2.py', 102, 25, 'def keyworded(*arg1, arg2=1):\n'))

SyntaxError: ('invalid syntax', ('/turnkey/non/github-watchlist/eggs/tmpvtTZUo/linecache2-1.0.0-py2.7.egg/linecache2/tests/inspect_fodder2.py', 102, 25, 'def keyworded(*arg1, arg2=1):\n'))
````
But I reran it and it all seems ok now... So I continued on and all seemed well until I tried to add a heap of repos to my watchlist. All looks good until it actually tries to add (after I say "Yes"). 
````
Traceback (most recent call last):
  File "bin/update-watchlist", line 14, in <module>
    sys.exit(watchlist.command.update_command())
  File "/turnkey/non/github-watchlist/watchlist/command.py", line 93, in update_command
    UpdateCommand(config)(confirmed=args.confirmed)
  File "/turnkey/non/github-watchlist/watchlist/command.py", line 27, in __call__
    SubscriptionsUpdater(self.config).update(data)
  File "/turnkey/non/github-watchlist/watchlist/updater.py", line 12, in update
    self.create_subscriptions(data['watch'])
  File "/turnkey/non/github-watchlist/watchlist/updater.py", line 21, in create_subscriptions
    payload=watch_payload)
  File "/turnkey/non/github-watchlist/watchlist/github.py", line 20, in put
    response.raise_for_status()
  File "/turnkey/non/github-watchlist/eggs/requests-2.6.2-py2.7.egg/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
````

**Comment by JedMeister** [comment]
Just relooking at this in the light of day... When I first run bin/update-watchlist`` I get this warning:
````
/turnkey/non/github-watchlist/eggs/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
````
Is that perhaps why I'm getting a 404?

**Comment by jone** [comment]
I'm not quite sure what's happening here.
Probably the script tries to set the subscriptions on a private repository, for which the script's access token has no privileges (github does not return `401 Unauthorized` but `404 Not Found` when accessing private repositories).

Can you verify that your access token at github has the scope `repo`?
![bildschirmfoto 2015-04-29 um 08 23 35](https://cloud.githubusercontent.com/assets/7469/7385581/0f1ac340-ee49-11e4-9dfc-afc7795ce606.png)

**Comment by JedMeister** [comment]
Sorry I was a bit slow getting back to you. That was exactly the problem...  Thanks for the time saved! :+1:
